# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c9dWV1IeyGvKa6idH5d9eMdpohcUQ4Q1
"""

n=int(input("Enter the number of students:"))
studlist=[]
for i in range(0,n):
  stud={}
  stud['name']=input("\nEnter name:")
  stud["branch"]=input("Enter branch:")
  stud["roll no"]=int(input("Enter roll no:\n"))
  studlist.append(stud)
print("\nName  Branch  Roll no\n")

for i in range(0,n):  
  print(studlist[i])