# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c77qIbAqUvsWoPBeg-qRDErDjchbGYyj
"""

d = {'AREENA': 10, 'VEENA': 3, 'GOPIKA': 15, 'AMRITHA': 8}
print("Dictionary : ",d)
print("Ascending order using keys : ",sorted(d.keys()))
print("Ascending order using values : ",sorted(d.values()))
print("Descending order using keys :",sorted(d.keys(),reverse=True))
print("Descending order using values :",sorted(d.values(),reverse=True))
print("Descending order using keys and values :",sorted(d.items()))
print("Descending order using keys and values :",sorted(d.items(),reverse=True))