# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Df8w8TqaBr1urbqtfIUHPNPcL18iokO0
"""

def sum():
  n=int(input("Enter the limit : "))
  s=0
  for i in range(1,n+1):
    s=s+i
  print("Sum :",s)
sum()