# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lSnWMLimrkyBjz9jPDMx7ZoVZokHIaOp
"""

string = input("Enter a String : ")  
count = 0  
for i in range(0, len(string)):
    if(string[i] != ' '):
        count = count + 1  
print("Total number of characters in a string: " + str(count))