# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19tQAPBOOejN0rCNoMvC60ZsDDcRROzNI
"""

def fibonacci():
  a=0
  b=1
  n=int(input("Enter the limit :"))
  for i in range(a,n):
    print(a)
    temp=a+b
    a=b
    b =temp
fibonacci()