# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10dl-UulveZ3WLKgT83xl_BFjgjuD_uP0
"""

def add(a,b):
  return a+b
def subtract(a,b):
  return a-b
def multiply(a,b):
  return a*b
def divide(a,b):
  return a/b
def mod(a,b):
  return a%b
def power(a,b):
  return a**b
print("Select operation\n1.Add\n2.Subtract\n3.Multiply\n4.Divide\n5.Modulus\n6.Power")
choice=input("enter your choice(1/2/3/4/5/6) :")
num1=int(input("Enter the number"))
num2=int(input("Enter the number"))
if choice=="1":
  print(num1,"+",num2,"=",add(num1,num2))
elif choice=="2":
  print(num1,"-",num2,"=",subtract(num1,num2))
elif choice=="3":
  print(num1,"*",num2,"=",multiply(num1,num2))
elif choice=="4":
  print(num1,"/",num2,"=",divide(num1,num2))
elif choice=="5":
  print(num1,"%",num2,"=",mod(num1,num2))
elif choice=="6":
  print(num1,"**",num2,"=",power(num1,num2))
else:
  print("Invalid choice")