# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ECq5zi95KKy2EXxdAYsX7Au9NYRcYKmu
"""

def binary(b):
  d=0
  i=1
  while(b!=0):
    rem=b%10
    d=d+rem*i
    i=i*2
    b=b//10
  return d
b=int(input("Enter the binary value :"))
bi=binary(b)
print(bi)