# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D-pPHlonLCdvKLRvhtAHjgiRChGSIFCW
"""

try:
  a = int(input("Enter a:"))
  b = int(input("Enter b:"))
  c = a/b 
  print("a/b = %d"%c)
except Exception:
  print("Can't divide by zero")
  print(Exception)
else:
  print("Hi I am else block")