# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-UYtXf_svHd2B8fpLT3R20EYxUllVuwg
"""

def exchange(str):
  return str[-1:]+str[1:-1]+str[:1]
string=input("Enter the string :")
print("String after exchange")
print(exchange(string))