# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ht7AzhuACKW77ptn4YWPH3Nmvs3FtcxD
"""

sen=input("enter a string :")
a=[]
str=sen.split()
for i in str:
  if i not in a:
    a.append(i)
print("List",a)
count=0
for i in range(len(sen)):
  if(sen[i]=='a'):
    count=count+1
print("The occurance of a :",count)