# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JSOz6u2q_vqNPJ3VR0MfJUbYany2Cb6F
"""

try:
  num = int(input("Enter a positive integer: "))
  if(num <= 0):
    raise ValueError("That is a negative number!")
except ValueError as e:
  print(e)