# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ORHfRkCInAz3PaZz5kvPY2Elp2uJNMvr
"""

try:
  fileptr = open("abc.txt","r")
  try:
     fileptr.write("Hi I am good")
  finally:
    fileptr.close() 
    print("file closed")
except:
  print("Error")