# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UsYnG8YRiqFHm5f48rAkAuht10AwEzLE
"""

def stringadd(str1):
  length = len(str1)

  if length > 2:
    if str1[-3:] == 'ing':
      str1 += 'ly'
    else:
      str1 += 'ing'

  return str1
print(stringadd('Sleep'))
print(stringadd('Wait'))
print(stringadd('Sing'))