# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nJHdWLV20hxQ06KDN38-7-Dl6OZvRoK3
"""

student={}
n=int(input("Enter the no. of students:"))
for i in range(0,n):
  a=input("Enter the name of student:")
  student[a]=int(input("Enter the mark of student:"))
print(student)
b=[]
b+=student.keys()
b.sort()
for i in range(n):
  print("%s\t:\t%d" %(b[i],student[b[i]]))