# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_IIHk9NWYLv5mdhS97-OhWF4eUPZ6ij6
"""

def getmax(b):
    return max(b,key=len)
a=[]
n= int(input("Enter the number of elements in list:"))
for x in range(0,n):
    e=input("Enter Element : ")
    a.append(e)
print("The Longest word in the list is :", getmax(a))