# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xiH0iHyhH7XK7xyuW_ErF22bkxFt7i4p
"""

def factorial(n):
   if (n == 1):
       return n
   else:
       return n*factorial(n-1)

num=int(input("Enter a number :"))


if (num < 0):
   print("factorial does not exist for negative numbers")
elif (num == 0):
   print("The factorial of 0 is 1")
else:
   print("The factorial of", num, "is",factorial(num))