# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pkuG_qiXcYUNRyjAvjOjJv7xsVX9Kg1v
"""

def palindrome():
  n=int(input("Enter the number :"))
  temp=n
  rev=0
  while(n>0):
    d=n%10
    rev=rev*10+d
    n=n//10
  if(temp==rev):
    print("The number is a palindrome")
  else:
    print("The number is not a palindrome")
palindrome()