# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Gp-Cu0LZdmH-yoHeSgnsPnN1U8h0rX3
"""

x={"name":"AREENA","age":21,"year":2000}
y={"sub":"MCA","year":2022,"class":1}
print("First dictionary",x)
print("Second dictionary",y)
x.update(y)
print("Dictionary after merging",x)